### ISSUE TITLE
Jaco-Assistant / Scribosermo setup?

### ISSUE THREAD

**Issue by fquirin** [domcross/german-stt-evaluation#1]
Hi Dominik,

these are some nice tests :+1: . I was wondering if you have any documentation on how you got Scribosermo running? It looks like performance and size are very good and I'd love to add it to the [SEPIA STT-Server](https://github.com/SEPIA-Framework/sepia-stt-server), but I have some difficulties getting started (maybe [this](https://gitlab.com/Jaco-Assistant/Scribosermo/-/blob/master/extras/exporting/testing_stream.py) could be an entry point?). 

Have you ever tried running it on a Raspberry Pi?

Oh and btw did you do some tests with Coqui as well?

**Comment by domcross** [comment]
Hi Florian,

> I was wondering if you have any documentation on how you got Scribosermo running?

I plan to publish the code-snippets I have used for evaluation soon. 

> Have you ever tried running it on a Raspberry Pi?

Not yet, might give it a try on a RPI3 in the future...

> Oh and btw did you do some tests with Coqui as well?

The tflite-version of DeepSpeech-German-v0.9.0 model was tested with Coqui-STT as well, but the results were not too good (WER: 33.74, CER: 12.54).

**Comment by fquirin** [comment]
Thanks for the info, I'll keep an eye out for updates :slightly_smiling_face: 

> Not yet, might give it a try on a RPI3 in the future...

I'd be very interested in the results! Vosk runs smoothly on RPi4 and I'm already very happy with the performance (especially when you train your own LMs), but I'd like to offer a broader range of engines and Scribosermo looks really impressive in your tests. The RTF gives me hope that it might work on RPis as well ^^

**Comment by fquirin** [comment]
Hi @domcross , I saw your update and decided to give it a try on Raspberry Pi OS aarch64 version.

Do you maybe happen to have a Wheel for 'ds_ctcdecoder' that runs on Python 3.7 aarch64 :sweat_smile: ... I saw your Python 3.6 version and tried to downgrade the Pi but v3.6 is giving me a lot of other headaches :see_no_evil:

**Comment by domcross** [comment]
A cp37/armv7-wheel for RPI3 can be found here, maybe this works for RPI4/aarch64 as well?
https://gitlab.com/Jaco-Assistant/Scribosermo/-/tree/master/extras/misc

**Comment by fquirin** [comment]
Ty, I've seen that folder and noticed there might be a build script as well, but unfortunately the 32bit Wheels won't work on aarch64 :-(

**Comment by domcross** [comment]
I will use the additional hour we gain through time savings tonight by trying to build a wheel for cp37/aarch64...

**Comment by fquirin** [comment]
:star_struck: gl :grinning:

**Comment by domcross** [comment]
Was probably easier than I thought, please try this:
https://github.com/domcross/DeepSpeech-for-Jetson-Nano/releases/download/ds_ctcdecoder-0.10.0a3/ds_ctcdecoder-0.10.0a3-cp37-cp37m-linux_aarch64.whl

**Comment by fquirin** [comment]
pip installation worked :partying_face:  thanks a lot!
working on the remaining packages now ^^
I'm building wheels for 'numpy' and 'tokenizers' (which requires Rust compiler) right now. Next stop will be librosa :crossed_fingers:

**Comment by fquirin** [comment]
A little update: It works very well on Raspberry Pi4 2GB aarch64 :grinning: 

I've collected all my tests here: https://github.com/fquirin/scribosermo-stt-setup

There is one thing that confuses me though. Do you understand the license of the model checkpoints? It seems Daniel took training weights for QuartzNet from [Nvidia's NGC](https://ngc.nvidia.com/catalog/models?query=%20label%3A%22QuartzNet%22) page which means the terms of usage apply and probably prohibit usage on certain systems or under certain conditions which are unclear to me :-/

**Comment by domcross** [comment]
I wasn't aware that the training weights were taken vom Nvidia. 
To avoid any legal/license issues I did not include the pretrained models on purpose ;-)

**Comment by fquirin** [comment]
Smart move ;-) ... I didn't dare to host them in the Git repo either :-(, hope we can resolve this issue somehow.

**Comment by domcross** [comment]
Closing as issue is resolved.
